Sadak@ Web/sadakaupdate/src/Entity/Comment.php
<?php

namespace App\Entity;

use App\Repository\CommentRepository;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;

/**
 * @ORM\Entity(repositoryClass=CommentRepository::class)
 */
class Comment
{
    use TimestampableEntity;
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $OrganiserName;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\ManyToOne(targetEntity=Event::class, inversedBy="comments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $event;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isDeleted=false;



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getOrganiserName(): ?string
    {
        return $this->OrganiserName;
    }

    public function setOrganiserName(string $OrganiserName): self
    {
        $this->OrganiserName = $OrganiserName;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getEvent(): ?Event
    {
        return $this->event;
    }

    public function setEvent(?Event $event): self
    {
        $this->event = $event;

        return $this;
    }

    public function getIsDeleted(): ?bool
    {
        return $this->isDeleted;
    }

    public function setIsDeleted(bool $isDeleted): self
    {
        $this->isDeleted = $isDeleted;

        return $this;
    }


}

Sadak@ Web/sadakaupdate/src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;


/**
 * @ORM\Entity(repositoryClass=EventRepository::class)
 */
class Event
{
    use TimestampableEntity;
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank (message="")
     */
    private $eventName;

    /**
     * @ORM\Column(type="datetime")
     */
    private $eventDate;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\NotBlank()
     */
    private $eventDateF;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank
     */
    private $eventContent;

    /**
     * @ORM\Column(type="string", length=255)

     *
     */
    private $eventImage;

    /**
     * @ORM\Column(type="integer")
     * @Assert\GreaterThan(10)
     * @Assert\PositiveOrZero
     */
    private $eventParticipants;

    /**
     * @ORM\Column(type="datetime")
     */
    private $publishedAt;

    /**
     * @Gedmo\Slug(fields={"eventName","eventName","eventName"})
     * @ORM\Column(type="string", length=100,unique=true)

     */
    private $slug;



    /**
     * @ORM\Column(type="integer")
     */
    private $heartCount=0;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="event",fetch="EXTRA_LAZY")
     * @ORM\OrderBy({"createdAt" = "DESC"})
     */
    private $comments;

    /**
     * @ORM\ManyToOne(targetEntity=CategoryEvent::class, inversedBy="eventt")
     */
    private $categoryEvent;

    /**
     * @ORM\ManyToMany(targetEntity=Tag::class, inversedBy="events")
     */
    private $tags;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="events")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotBlank()
     */
    private $eventOrganiser;





    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->tags = new ArrayCollection();
    }



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEventName(): ?string
    {
        return $this->eventName;
    }

    public function setEventName(string $eventName): self
    {
        $this->eventName = $eventName;

        return $this;
    }

    public function getEventDate(): ?\DateTimeInterface
    {
        return $this->eventDate;
    }

    public function setEventDate(\DateTimeInterface $eventDate): self
    {
        $this->eventDate = $eventDate;

        return $this;
    }

    public function getEventDateF(): ?\DateTimeInterface
    {
        return $this->eventDateF;
    }

    public function setEventDateF(\DateTimeInterface $eventDateF): self
    {
        $this->eventDateF = $eventDateF;

        return $this;
    }

    public function getEventContent(): ?string
    {
        return $this->eventContent;
    }

    public function setEventContent(string $eventContent): self
    {
        $this->eventContent = $eventContent;

        return $this;
    }

    public function getEventImage(): ?string
    {
        return $this->eventImage;
    }

    public function setEventImage(string $eventImage): self
    {
        $this->eventImage = $eventImage;

        return $this;
    }

    public function getEventParticipants(): ?int
    {
        return $this->eventParticipants;
    }

    public function setEventParticipants(int $eventParticipants): self
    {
        $this->eventParticipants = $eventParticipants;

        return $this;
    }

    public function getPublishedAt(): ?\DateTimeInterface
    {
        return $this->publishedAt;
    }

    public function setPublishedAt(\DateTimeInterface $publishedAt): self
    {
        $this->publishedAt = $publishedAt;

        return $this;
    }
    public function isPublished(): bool
    {
//        $date  = new \DateTime();
//        if ($date->diff($this->publishedAt)){
//            return true;
//        } else
//            return  false;
        return $this->publishedAt !== null;

    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }



    public function getHeartCount(): ?int
    {
        return $this->heartCount;
    }

    public function setHeartCount(int $heartCount): self
    {
        $this->heartCount = $heartCount;

        return $this;
    }
    public function incrementHeartCount(): self
    {
        $this->heartCount = $this->heartCount + 1;

        return $this;
    }
    public function getImagePath()
    {
        return 'images/'.$this->getEventImage();
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getNonDeletedComments(): Collection
    {
        $criteria = EventRepository::createNonDeletedCriteria();
        return $this->comments->matching($criteria);
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setEvent($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getEvent() === $this) {
                $comment->setEvent(null);
            }
        }

        return $this;
    }

    public function getCategoryEvent(): ?CategoryEvent
    {
        return $this->categoryEvent;
    }

    public function setCategoryEvent(?CategoryEvent $categoryEvent): self
    {
        $this->categoryEvent = $categoryEvent;

        return $this;
    }

    /**
     * @return Collection|Tag[]
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        $this->tags->removeElement($tag);

        return $this;
    }

    public function getEventOrganiser(): ?User
    {
        return $this->eventOrganiser;
    }

    public function setEventOrganiser(?User $eventOrganiser): self
    {
        $this->eventOrganiser = $eventOrganiser;

        return $this;
    }



    public function validate(ExecutionContextInterface $context, $payload)
    {
        if (stripos($this->getEventName(), 'Test') !== false) {
            $context->buildViolation('Um.. the Test kinda makes us nervous')
                ->atPath('eventName')
                ->addViolation();
        }
    }
}

Sadak@ Web/sadakaupdate/src/Controller/EventController.php
<?php

namespace App\Controller;

use App\Entity\Comment;
use App\Entity\Event;
use App\Entity\User;
use App\Form\CommentType;
use App\Form\EventFormType;
use App\Repository\CommentRepository;
use App\Repository\EventRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Knp\Snappy\Pdf;
use Psr\Log\LoggerInterface;
use Symfony\Bridge\Twig\Mime\TemplatedEmail;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Address;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

class EventController extends BaseController
{
    /**
     * @Route("/", name="app_homepage")
     */
//    public function homepage(EventRepository $rep) {
//
//        $events=$rep->findAllPublishedOrderedByNewest();
//
//
//        return $this->render('event/homepage.html.twig',[
//            'events'=>$events,
//        ]);
//    }

    public function homepage(EventRepository $repository, Request $request, PaginatorInterface $paginator)
    {
        $q = $request->query->get('q');
        $queryBuilder = $repository->getWithSearchQueryBuilder($q);

        $pagination = $paginator->paginate(
            $queryBuilder, /* query NOT result */
            $request->query->getInt('page', 1)/*page number*/,
            6/*limit per page*/
        );

        return $this->render('event/homepage.html.twig', [
            'pagination' => $pagination,
        ]);
    }





    /**
     * @Route("/news/{slug}", name="event_show")
     */
    public function show(Event $event,EntityManagerInterface $em, Request $request)
    {

        $user=$this->getUser();
        $form = $this->createForm(CommentType::class);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            /** @var Comment $comment */
            $comment= $form->getData();
            $comment->setOrganiserName($user->getFirstName());
            $comment->setEvent($event);
            $em->persist($comment);
            $em->flush();

            $this->addFlash("success","Event Created ! Berakallahou Fik");

        }


        return $this->render('event/show.html.twig', [
            'event'=>$event,'user'=>$user, 'commentForm' => $form->createView()

        ]);
    }

    /**
     * @Route("/news/{slug}/heart", name="event_toggle_heart", methods={"POST"})
     * @IsGranted("ROLE_USER")
     */

    public function toggleEventHeart(Event $event,LoggerInterface $logger,EntityManagerInterface $em)
    {
        $event->incrementHeartCount();
        $em->flush();

        $logger->info('Article is being hearted!');
        return new JsonResponse(['hearts' => $event->getHeartCount()]);
    }


    /**
     * @Route("/email/{id}", name="email")
     */
    public function sendEmail($id,MailerInterface $mailer,Pdf $pdf,EventRepository $repo)
    {

        $event=$repo->find($id);
        //Generation du pdf
        $pdf->generateFromHtml(
            $this->renderView(
                'email/EventPDF.html.twig',
                array(
                    'some' => $event
                )
            ),
            $event->getEventName() . ".pdf"
        );

        $email = (new TemplatedEmail())
            ->from(new Address('ahmed@esprit.tn', 'Sadaka@'))
            ->to(new Address($this->getUser()->getEmail()))
            ->subject('Verification des famille')
            ->htmlTemplate('email/emailEvent.html.twig')
            ->context([
                'event' => $event
            ])
            ->attachFromPath($event->getEventName() . '.pdf');


        $mailer->send($email);
        return  Response::create("Success");
    }



}

Sadak@ Web/sadakaupdate/templates/event/homepage.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container">
        <div class="row">

            <!-- Article List -->

            <div class="col-sm-12 col-md-8">

                <!-- H1 Article -->
                {% block slide %}
                    <!DOCTYPE html>
                    <html>
                    <meta name="viewport" content="width=device-width, initial-scale=1">
                    <style>




                        /* Position the image container (needed to position the left and right arrows) */
                        .container {
                            position: relative;
                        }

                        /* Hide the images by default */
                        .mySlides {
                            display: none;
                        }

                        /* Add a pointer when hovering over the thumbnail images */
                        .cursor {
                            cursor: pointer;
                        }

                        /* Next & previous buttons */
                        .prev,
                        .next {
                            cursor: pointer;
                            position: absolute;
                            top: 40%;
                            width: auto;
                            padding: 16px;
                            margin-top: -50px;
                            color: white;
                            font-weight: bold;
                            font-size: 20px;
                            border-radius: 0 3px 3px 0;
                            user-select: none;
                            -webkit-user-select: none;
                        }

                        /* Position the "next button" to the right */
                        .next {
                            right: 0;
                            border-radius: 3px 0 0 3px;
                        }

                        /* On hover, add a black background color with a little bit see-through */
                        .prev:hover,
                        .next:hover {
                            background-color: rgba(0, 0, 0, 0.8);
                        }

                        /* Number text (1/3 etc) */
                        .numbertext {
                            color: #f2f2f2;
                            font-size: 12px;
                            padding: 8px 12px;
                            position: absolute;
                            top: 0;
                        }

                        /* Container for image text */
                        .caption-container {
                            text-align: center;
                            background-color: #222;
                            padding: 2px 16px;
                            color: white;
                        }

                        .row:after {
                            content: "";
                            display: table;
                            clear: both;
                        }

                        /* Six columns side by side */
                        .column {
                            float: left;
                            width: 16.66%;
                        }

                        /* Add a transparency effect for thumnbail images */
                        .demo {
                            opacity: 0.6;
                        }

                        .active,
                        .demo:hover {
                            opacity: 1;
                        }
                    </style>
                    <body>

{#                    <h2 style="text-align:center">Slideshow Gallery</h2>#}

                    <div class="container">
                        <div class="mySlides">
                            <div class="numbertext">1 / 6</div>
                            <img src="{{ asset('images/35662.png') }}" style="width:100%">
                        </div>

                        <div class="mySlides">
                            <div class="numbertext">2 / 6</div>
                            <img src="{{ asset('images/35662.png') }}" style="width:100%">
                        </div>

                        <div class="mySlides">
                            <div class="numbertext">3 / 6</div>
                            <img src="{{ asset('images/35662.png') }}" style="width:100%">
                        </div>

                        <div class="mySlides">
                            <div class="numbertext">4 / 6</div>
                            <img src="{{ asset('images/35662.png') }}" style="width:100%">
                        </div>

                        <div class="mySlides">
                            <div class="numbertext">5 / 6</div>
                            <img src="{{ asset('images/35662.png') }}" style="width:100%">
                        </div>

                        <div class="mySlides">
                            <div class="numbertext">6 / 6</div>
                            <img src="{{ asset('images/35662.png') }}" style="width:100%">
                        </div>

                        <a class="prev" onclick="plusSlides(-1)">❮</a>
                        <a class="next" onclick="plusSlides(1)">❯</a>

                        <div class="caption-container">
                            <p id="caption"></p>
                        </div>

                        <div class="row">
                            <div class="column">
                                <img class="demo cursor" src="{{ asset('images/35662.png') }}" style="width:100%" onclick="currentSlide(1)" alt="The Woods">
                            </div>
                            <div class="column">
                                <img class="demo cursor" src="{{ asset('images/35662.png') }}" style="width:100%" onclick="currentSlide(2)" alt="Cinque Terre">
                            </div>
                            <div class="column">
                                <img class="demo cursor" src="{{ asset('images/35662.png') }}" style="width:100%" onclick="currentSlide(3)" alt="Mountains and fjords">
                            </div>
                            <div class="column">
                                <img class="demo cursor" src="{{ asset('images/35662.png') }}" style="width:100%" onclick="currentSlide(4)" alt="Northern Lights">
                            </div>
                            <div class="column">
                                <img class="demo cursor" src="{{ asset('images/35662.png') }}" style="width:100%" onclick="currentSlide(5)" alt="Nature and sunrise">
                            </div>
                            <div class="column">
                                <img class="demo cursor" src="{{ asset('images/35662.png') }}" style="width:100%" onclick="currentSlide(6)" alt="Snowy Mountains">
                            </div>
                        </div>
                    </div>

                    <script>
                        var slideIndex = 1;
                        showSlides(slideIndex);

                        function plusSlides(n) {
                            showSlides(slideIndex += n);
                        }

                        function currentSlide(n) {
                            showSlides(slideIndex = n);
                        }

                        function showSlides(n) {
                            var i;
                            var slides = document.getElementsByClassName("mySlides");
                            var dots = document.getElementsByClassName("demo");
                            var captionText = document.getElementById("caption");
                            if (n > slides.length) {slideIndex = 1}
                            if (n < 1) {slideIndex = slides.length}
                            for (i = 0; i < slides.length; i++) {
                                slides[i].style.display = "none";
                            }
                            for (i = 0; i < dots.length; i++) {
                                dots[i].className = dots[i].className.replace(" active", "");
                            }
                            slides[slideIndex-1].style.display = "block";
                            dots[slideIndex-1].className += " active";
                            captionText.innerHTML = dots[slideIndex-1].alt;
                        }
                    </script>

                    </body>
                    </html>


                {% endblock %}
                <!-- Supporting Articles -->
                {% for event in pagination %}
                <div class="article-container my-1">
                    <a href="{{ path('event_show', {slug: event.slug}) }}">
                        <img class="article-img" src="{{ asset(event.imagePath) }}">
                        <div class="article-title d-inline-block pl-3 align-middle">
                            <span>{{ event.eventName }}</span>
                            <small>({{ event.nonDeletedComments|length }} Comments )</small>
                            <br>
                            {% for tag in event.tags %}
                                <small>
                                    <span class="badge badge-light">{{ tag.name }}</span>
                                </small>
                            {% endfor %}
                            <br>
                            <span class="align-left article-details"><img class="article-author-img rounded-circle" src="{{ event.eventOrganiser.avatarUrl }}"> {{ event.eventOrganiser.firstName}}</span>
                            <span class="pl-5 article-details float-right">  {{event.publishedAt  ? event.publishedAt|ago :"unpub"}}</span>
                        </div>
                    </a>
                    {% if is_granted('ROLE_USER') %}
                    <button class="article-container my-1" style="border: 1px solid black;border-radius: 5px;background: grey;position: relative;margin-left: 200px;cursor: p">
                        <a href="{{ path('email',{
                            id: event.id
                        }) }}">Participer</a></button>
                    {% else %}
                        <button class="article-container my-1" style="border: 1px solid black;border-radius: 5px;background: grey;position: relative;margin-left: 200px;cursor: p">
                            <a href="{{ path('app_login') }}">Login</a></button>
                    {% endif %}
                </div>

                {% endfor %}

                {{ knp_pagination_render(pagination) }}

            </div>

            <!-- Right bar ad space -->


            <div class="col-sm-12 col-md-4 text-center">
                <div class="ad-space mx-auto mt-1 pb-2 pt-2">
                    <img class="advertisement-img" src="{{ asset('images/space-ice.png') }}">
                    <p><span class="advertisement-text">New:</span> Space Ice Cream!</p>
                    <button class="btn btn-info">Buy Now!</button>
                </div>

                <div class="quote-space pb-2 pt-2 px-5">
                    <h3 class="text-center pb-3">Trending Quotes</h3>
                    <p><i class="fa fa-comment"></i> "Our two greatest problems are gravity and paperwork. We can lick gravity, but sometimes the paperwork is overwhelming." <br>— <a href="https://en.wikipedia.org/wiki/Wernher_von_Braun">Wernher von Braun, Rocket Engineer</a></p>

                    <p class="pt-4"><i class="fa fa-comment"></i> "Let's face it, space is a risky business. I always considered every launch a barely controlled explosion." <br>— <a href="https://en.wikipedia.org/wiki/Aaron_Cohen_(Deputy_NASA_administrator)">Aaron Cohen, NASA Administrator</a></p>

                    <p class="pt-4"><i class="fa fa-comment"></i> "If offered a seat on a rocket ship, don't ask what seat. Just get on."<br>— <a href="https://en.wikipedia.org/wiki/Christa_McAuliffe">Christa McAuliffe, Challenger Astronaut</a>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

Sadak@ Web/sadakaupdate/templates/event/show.html.twig
{% extends 'content_base.html.twig' %}

{% block title %}Read: {{ event.eventName}}{% endblock %}

{% block content_body %}
                    <div class="row">
                        <div class="col-sm-12">
                            <img class="show-article-img" src="{{ asset(event.imagePath) }}">
                            <div class="show-article-title-container d-inline-block pl-3 align-middle">
                                <span class="show-article-title ">{{ event.eventName }}</span>
                                <br>
                                <span class="align-left article-details"><img class="article-author-img rounded-circle" src="{{ event.eventOrganiser.avatarUrl }}"> {{ event.eventOrganiser.firstName }}</span>
                                <span class="pl-2 article-details">
                                   {{event.publishedAt  ? event.publishedAt|ago :"unpub"}}
                                </span>
                                <span class="pl-2 article-details">
                                     <span class="js-like-article-count"> {{ event.heartCount }}</span>
                                    <a href="{{ path('event_toggle_heart',{slug:event.slug}) }}" class="fa fa-heart-o like-article js-like-article"></a>
                                </span>
                                <span class="pl-2 article-details">
                                   {% for tag in event.tags %}

                                          <span class="badge badge-secondary">{{ tag.name }}</span>

                                   {% endfor %}
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="article-text">
                                {{ event.eventContent | markdown}}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <p class="share-icons mb-5"><span class="pr-1">Share:</span> <i class="pr-1 fa fa-facebook-square"></i><i class="pr-1 fa fa-twitter-square"></i><i class="pr-1 fa fa-reddit-square"></i><i class="pr-1 fa fa-share-alt-square"></i></p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <h3><i class="pr-3 fa fa-comment"></i>{{ event.nonDeletedComments|length }} Comments</h3>
                            <hr>

                            <div class="row mb-5">
                                <div class="col-sm-12">
                                    <img class="comment-img rounded-circle" src="{{ asset('images/astronaut-profile.png') }}">
                                    <div class="comment-container d-inline-block pl-3 align-top">
                                        <span class="commenter-name">{{ user.firstName}} {{ user.lastName }}</span>
{#                                        <div class="form-group">#}
{#                                            <textarea class="form-control comment-form" id="articleText" rows="1"></textarea>#}
{#                                        </div>#}
{#                                        <button type="submit" class="btn btn-info">Comment</button>#}
                                        {% block comm %}
                                            {{ form_start(commentForm) }}

                                            {{ form_row(commentForm.content) }}


                                            <button type="submit" class="btn btn btn-info">Comment</button>
                                            {{ form_end(commentForm)}}
                                        {% endblock %}
                                    </div>
                                </div>
                            </div>

                            {% for comment in event.nonDeletedComments %}
                                <div class="row">
                                    <div class="col-sm-12">
                                        <img class="comment-img rounded-circle" src="{{ asset('images/alien-profile.png') }}">
                                        <div class="comment-container d-inline-block pl-3 align-top">
                                            <span class="commenter-name">{{ comment.organiserName }}</span>
                                            <small>about {{ comment.createdAt |ago }}</small>
                                            {% if comment.isDeleted %}
                                                <span class="fa fa-close"> Deleted</span>
                                            {% endif %}
                                            <br>
                                            <span class="comment"> {{ comment.content }}</span>
                                            <p><a href="#">Reply</a></p>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}

                        </div>
                    </div>


{% endblock %}

{% block javascripts %}
    {{ parent() }}
<script src="{{ asset('js/article_show.js') }}"></script>

{% endblock %}